export ADQM_OUT='/home/junshen/AutoDQM/runoffline/out'
export ADQM_PLUGINS='/home/junshen/AutoDQM/plugins'
export ADQM_CONFIG='/home/junshen/AutoDQM/config'
export ADQM_DB='/home/junshen/AutoDQM/runoffline/db'
export ADQM_TMP='/home/junshen/AutoDQM/runoffline/tmp'
export ADQM_SSLCERT='/home/junshen/AutoDQM/cern-cert.public.pem'
export ADQM_SSLKEY='/home/junshen/AutoDQM/cern-cert.private.key'
export ADQM_CACERT='/home/junshen/.globus/myCertificate.p12'
